### PR TITLE
refactor!: add API implementation close #20

### LINKED ISSUE #20: Component API
I designed an api for the component to be used as a library.

I give an example below of how it would be used along with some type definitions.

@josoriom note that compared to your current implementation:
- This is only the visible part exposed to the user. This is not "new" state, it's state that is derived from the existing reducer's state. Some state from the reducer should not be exposed to the user.
- The type definitions are not strict, you can adapt them to better fit your current implementation.
- I added labels to the type of an ROI. I think displaying labels in ROIs is something that is missing in the current implementation.
- I added a "mode" state. Mouse events should have different effects weather in the "draw" or "select" state. In "draw" mode you can draw new ROIs with click-drag-release. In "select" mode you cannot draw new rois, you can only select existing rois.

```tsx
import { CSSProperties } from 'react';
import {
  RoiContainer,
  RoiProvider,
  RoiBox,
  useRoiState,
  useRoiActions,
} from 'react-roi';

// Defined by the library
interface Roi<TData = unknown> {
  id: string;
  label?: string;
  x: number;
  y: number;
  width: number;
  height: number;
  isMoving: boolean;
  isResizing: boolean;
  style: CSSProperties;
  editStyle: CSSProperties;
  data?: TData;
}

// Defined by the library
type CommittedRoi<TData = unknown> = Omit<
  Roi<TData>,
  'isMoving' | 'isResizing'
>;

// Defined by the user
interface RoiData {
  // We can associate custom data to the ROI
  // For example we might want to define a pseudonymization method (pixelate, blur, fill etc...) here
  // The component that needs the ROIs can access this data along all the other properties when the roi updates.
  blurMethod: 'pixelate' | 'blur' | 'fill';
}

const initialRois: CommittedRoi<RoiData>[] = [
  {
    id: '550e8400-e29b-41d4-a716-446655440000',
    x: 100,
    y: 50,
    width: 100,
    height: 100,
    style: {
      backgroundColor: 'red',
      opacity: 0.6,
    },
    // The style of the ROI changes to those values when it's being moved or resized
    editStyle: {
      backgroundColor: 'pink',
      opacity: 0.4,
    },
    data: {
      blurMethod: 'pixelate',
    },
  },
];

// Example of usage in a component
function MyComponent() {
  return (
    // RoiProvider provides the context needed by Toolbar, ReactRoiContainer and TransformedImage
    // It is initialized with the ROIs to start with
    // initialRois's type is CommitedRoi<RoiData>[]
    <RoiProvider<RoiData> initialRois={initialRois}>
      <Toolbar />
      <ImageWithRois />
      <TransformedImage />
    </RoiProvider>
  );
}

function Toolbar() {
  const { mode, selectedRoi } = useRoiState<RoiData>();
  const { setMode, createRoi, updateRoi } = useRoiActions<RoiData>();

  return (
    <div>
      <div>Mode: {mode}</div>
      <button type="button" onClick={() => setMode('select')}>
        Select
      </button>
      <button type="button" onClick={() => setMode('draw')}>
        Draw
      </button>

      <button
        type="button"
        onClick={() =>
          // Takes a new CommitedRoi<RoiData> as argument
          createRoi({
            id: crypto.randomUUID(),
            // All the following roi properties are optional

            // When creating a new ROI, the default position is the center, reasonably sized based on the size of the target
            x: 100,
            y: 50,
            width: 100,
            height: 100,
            label: 'My new roi',
            // All styles are optional and created randomly if not provided
            style: {
              backgroundColor: '#ff5500',
              opacity: 0.6,
            },
            editStyle: {
              backgroundColor: '#ffaa00',
              opacity: 0.4,
            },
            data: {
              blurMethod: 'pixelate',
            },
          })
        }
      >
        Create ROI
      </button>
      <button
        type="button"
        onClick={() => {
          // Update the color of the selected ROI
          // First argument: roi to update (string)
          // Second argument: update data (Partial<CommitedRoi<RoiData>>)
          updateRoi(selectedRoi, {
            style: {
              backgroundColor: 'green',
              opacity: 0.6,
            },
            editStyle: {
              backgroundColor: 'lightgreen',
              opacity: 0.4,
            },
          });
        }}
      />
    </div>
  );
}

function ImageWithRois() {
  // The type of rois is Roi<RoiData>[]
  const { rois } = useRoiState<RoiData>() as { rois: Roi<RoiData>[] };
  return (
    // This component renders the target image and all the ROIs
    // it throws if rendered without an explicit provider on top of it
    // And handles the mouse interactions to edit the rois
    // It's possible to disable edition interactions by setting the readOnly prop to true
    <RoiContainer target={<img src="" />} readOnly>
      {rois.map((roi) => (
        <RoiBox key={roi.id} roi={roi} />
      ))}
    </RoiContainer>
  );
}

function TransformedImage() {
  // The api provides a different list of ROIs, which only changes when the movement
  // of an roi is finished (so when the user releases the mouse after moving or resizing)
  // The shape of the roi objects are the same which need to be fed as initial values to the RoiProvider
  // The type of commitedRois is CommitedRoi<RoiData>[]
  const { commitedRois } = useRoiState<RoiData>();

  // e.g. create the pseudonymized image in an effect
  return <img src="" />;

  // the result of this hook can also be used to send the ROIs to the backend
}
```

### PR DESCRIPTION
**Pull request by josoriom**

### CODE REVIEW

**Review by stropitek — COMMENTED** [review]
Bugs:
- [x] Use crosshair cursor when in drawing mode
- [x] Do no use hand cursor when over roi when in drawing mode
- [ ] Background color flickers when selecting
- [x] Update coordinates of roi with `updateRoi` does not update the corners of the selected roi
- [ ] Label does not move alongn with roi when draging
- [ ] Double clicking anywhere on the roi container selects the dom (put a blue overlay)



Would be nice to have features:
- [ ] Cancel drawing of a roi with Esc key
- [ ] Click outside of ROI unselects currently selected ROI
- [ ] Optimize rendering (I will take care of that at the end)


Code:
- [ ] Don't suffix types with `Type`
- [ ] `useRoiActions` should return a stable reference (you are creating a new object on each render of a component that uses this hook)

**Comment by stropitek** [comment]
To avoid this flicker effect when selecting, I think you can make the ROI semi-transparent only once it started moving by more than a small amount of pixels.

https://github.com/zakodium-oss/react-roi/assets/4118690/4288d254-5314-4af7-aadc-3974e1422954

**Comment by stropitek** [comment]
https://github.com/zakodium-oss/react-roi/assets/4118690/cbb052cb-d5e9-44b2-ae48-7e8b4c5ab357C

When drawing should always be crosshair (also when not over ROI)

**Comment by stropitek** [comment]
https://github.com/zakodium-oss/react-roi/assets/4118690/c2459fa1-1839-496e-85ea-35aa3f5e5f65

Corners should not be visible while drawing a new roi.

**Comment by stropitek** [comment]
https://github.com/zakodium-oss/react-roi/assets/4118690/e9c345bd-c8e8-4bb5-aaf5-db744b61c362

The ROI seems to be blocked as soon as the calculated new position go over the boundary. Instead the new position should be exactly on the boundary when it goes over.

**Comment by stropitek** [comment]
Why are `startPoint` and `endPoint` at the root level of the state? They seem to be related to the moving / resizing ROI. I think it would make more sense if they are at the level of the ROI instead.

**Comment by stropitek** [comment]
I think we need another hook `useCommitedRois` which updates only at the end of a move / resize / create / update action instead of on every state change.

This would allow to have a "live" preview that updates only at the end of the operation. It would be nice if your example did have such a "live" preview, instead of having to go to the "result" page.

**Comment by josoriom** [comment]
> Why are `startPoint` and `endPoint`, `delta` at the root level of the state? They seem to be related to the moving / resizing ROI. I think it would make more sense if they are at the level of the ROI instead.
> 
> Also I'm under the impression that the `delta` state could be removed entirely, it's not really used anywhere.

@stropitek The `startingPoint` is to the point (x, y) where the `onMouseDown` event is triggered. The `endPoint` represents the current cursor position, which changes as a result of the `onMouseMove` event within the `RoiContainer`. These points are for resizing/moving of the rois, as well to create new ones and updating the `ResizeBox`. I'm not sure whether this location within the state is is appropriate.

**Pull request merged**
